# Generated by Django 5.1.4 on 2024-12-25 13:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='shoes/empty.jpg', max_length=255, verbose_name='shoes/'),
        ),
    ]
