# Generated by Django 5.1.4 on 2024-12-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_shoe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
    ]
