# Generated by Django 5.1.4 on 2024-12-25 14:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='empty.jpg', max_length=255, verbose_name='Image'),
        ),
    ]
