# Generated by Django 5.1.4 on 2024-12-25 22:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_shoe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image1',
            field=cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image2',
            field=cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image3',
            field=cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image4',
            field=cloudinary.models.CloudinaryField(default='empty_q2cypk.png', max_length=255, verbose_name='Image4'),
        ),
    ]
