# Generated by Django 5.1.4 on 2024-12-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_shoe_image1_alter_shoe_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(default='empty_q2cypk.png', upload_to='Shoes/'),
        ),
    ]
