# Generated by Django 5.1.4 on 2024-12-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_pant_image1_pant_image2_pant_image3_pant_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantdetail',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shirtdetail',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
