# Generated by Django 5.1.4 on 2025-03-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_client_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='status',
            new_name='verificaton_status',
        ),
    ]
