# Generated by Django 5.1.4 on 2025-03-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_client_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=50)),
                ('product_ref', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('delta_quantity', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
    ]
